### ISSUE TITLE
`pm2 deploy` does not support yaml?

### ISSUE THREAD

**Issue by gera2ld** [Unitech/pm2#2256]
I have an `app.yml` like this:
``` yaml
apps:
  name: app
  script: ./index.js

deploy:
  production:
    ...
```

It works with commands below:
``` sh
$ pm2 start app.yml
$ pm2 restart app.yml
...
```

But deploy goes error:
``` sh
$ pm2 deploy app.yml production
```
Got this:
> app.yml environment is not defined in package.json file

After transforming app.yml to app.json, it works.

```
OS         : Mac OS X
node.js    : 5.10.1
PM2        : 1.1.1
```
