### ISSUE TITLE
Is it possible to set env specific options in application declaration file?

### ISSUE THREAD

**Issue by haimich** [Unitech/pm2#2264]
We have some issues with the `autorestart` feature and would like to set it to false on our development system. On all other environments we like the option to be on. Our processes.yml looks like this:

```yaml
apps:
  - script: node
    name: app
    args:
      - build/src/main.js
    env_development:
      NODE_ENV: development
      watch: build
      autorestart: false
    env_production:
      NODE_ENV: production
      autorestart: true
```
Unfortunately this doesn't work, the only thing that does is when you put the option on the top level, like so:

```yaml
apps:
  - script: node
    name: app
    autorestart: false
    ...
```

Are we using it the wrong way or is there simply no way to control these things on an environment level?
