### ISSUE TITLE
Logs directory is wrong during folder exists check.

### ISSUE THREAD

**Issue by yevhene** [Unitech/pm2#2411]
Project folder: `/home/user/app`
```
apps:
  - name: public-app
    script: apps/public-app/app.js
    cwd: apps/public-app
    out_file: ../../logs/public-app.out.log
    err_file: ../../logs/public-app.err.log
```

#### Expected behaviour

1. It checks if folder `/home/user/app/logs` exists;
2. It creates folder `/home/user/app/logs`;
3. It writes logs in `/home/user/app/logs` folder.

#### Actual behaviour

1. It checks if folder `/home/logs` exists;
2. It creates folder `/home/logs`;
3. It writes logs in `/home/user/app/logs` folder.

#### Steps to reproduce

1. Recreate folder structure;
2. Use example config;
3. Run pm2 start `config.yml`.

#### Software versions used

```
OS         : Ubuntu 15.10
node.js    : 6.7.0
PM2        : 2.0.15
```
