### ISSUE TITLE
Watch & reload resets to disabled bug

### ISSUE THREAD

**Issue by nodesocket** [Unitech/pm2#2441]
#### Expected behavior

Watch & reload flag stays persistent when an application is stopped and started manually. Application configured using `.yml` file.

#### Actual behavior

Watch & reload is set when an application is initially started, howerver if you run:

````shell
pm2 stop api-dev
pm2 start api-dev
````

You'll see watching has been reset to disabled.

#### Steps to reproduce

Start application with a `.yml` similar to:

````yaml
apps:
  - name: 'api-dev'
    cwd: /home/node/api
    script: ./api.js
    args: '--config config-dev.json'
    watch: true
    autorestart: true
    exec_mode: 'cluster'
    instances: -1
    combine_logs: true
````

Then run:

````shell
pm2 stop api-dev
pm2 start api-dev
pm2 info api-dev
````

#### Software versions used

**OS**: Ubuntu 16.04.1 LTS
**Node.js**: v6.5.0
**PM2**: 2.0.18
