### ISSUE TITLE
Breaking change - Process config loading failed []

### ISSUE THREAD

**Issue by nodesocket** [Unitech/pm2#3016]
Just upgraded to PM2 `2.5.0`and Node `v6.11.1` and now when I try to invoke:

     pm2 start pm2.yml

Getting`[PM2] Process config loading failed []`. Why? This used to work.

Here is the contents of `pm2.yml`:

```
apps:
  - name: 'blog.mydomain.net'
    cwd: /home/node/blog.mydomain.net
    script: ./index.js
    watch: false
    autorestart: true
    exec_mode: 'cluster'
    instances: -1
    combine_logs: true
    env:
      NODE_ENV: production
      MAILGUN_PASSWORD: xxxxxxxxxxxxxxxxxxxxxxxx
```
