### ISSUE TITLE
Feature: Ignore certain apps from process file when using restart/reload all

### ISSUE THREAD

**Issue by nofunatall** [Unitech/pm2#4055]
This is a feature request as per the title.

Starting/Restarting/Reloading/Stop etc with "all" argument effects all process within a process file.

We use a fairly large all in one file for all of our applications for our dev environments of which it's not ideal to ever load certain processes with the main set.

A work around is possible using the --only app1,app2 etc
Though for very large files this is not really ideal since we would have to specify dozens of apps using --only flag

### First and simple suggestion using a type of explicit flag
One suggestion is to have some sort of setting for apps within a process file with a setting name like "explicit_only" which would still have the app loaded but not in a started state when loading from a process file and additionally widespread actions like "restart all" would not effect the "explicit_only" apps.
Then to action on the "explicit_only" apps you would have another argument to use similar to "--only" (or even using the --only flag itself) where any app tagged as "explicit_only" will still be included if you explicitly specify it.

### Better suggestion using a tags feature
A second suggestion albeit likely more complex but in my opinion a better approach would be to have the ability to tag apps in the process files with any arbitrary string value
Example as YAML format (JSON just use arrays or something - I'm kinda bad with js/json):
```
apps: 
  - script: main/app.js
    name: main_app
    interpreter_args: --max-old-space-size=2048
    exec_mode: fork
    tags:
      - javascript
      - main
      - api

  - script: main/orders.js
    name: order_app
    interpreter_args: --max-old-space-size=2048
    exec_mode: fork
    tags:
      - javascript
      - main
      - api

  - script: test/test.js
    name: dev_test
    exec_mode: fork
    tags:
      - javascript
      - test

  - script: test/dev_api.js
    name: dev_api
    exec_mode: fork
    tags:
      - javascript
      - test
      - dev

  - script: chat/app.py
    name: chat_app
    cwd: chat
    interpreter: chat/env/bin/python
    interpreter_args: -u
    exec_mode: single
    tags:
      - python
      - chat
```

Then from the standpoint of the pm2 commands you could do things like "pm2 restart --tags javascript" to restart anything with the "javascript" tag. (Maybe additionally automatic tagging for things like the application language could be added)
Or for starting your test apps with the tag "test" and the tag "dev" you could do "pm2 start --tags test,dev".
