### ISSUE TITLE
pm2 on docker stucks at getMonitorData

### ISSUE THREAD

**Issue by mehmetegemen** [Unitech/pm2#4063]
## What's going wrong?

I am trying to deploy my application which consists of several microservices, each are in different docker containers. They hang at `pm2:client Calling daemon method Calling daemon method pm2:getMonitorData on rpc socket:/root/.pm2/rpc.sock` message and keeps printing same message(DEBUG is *).
## Supporting information

Here is my example Dockerfile
```
FROM keymetrics/pm2:latest-jessie
COPY ./ ./
ENV MONGO_URL=http://localhost:3007/slickpoll_polls
ENV DEBUG=*
EXPOSE 3002
RUN npm install
RUN npm install -D ts-node
RUN npm install -D typescript
RUN pm2 install typescript
CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]

```

and here is my docker-compose.yml

```
version: '3'

services:
    users-database:
        build: ./usersDatabase
        volumes:
            - ~/dbs/usersDatabase:/data/db
        ports:
            - 27017:3006
        networks: 
            - usersdb
    polls-database:
        build: ./pollsDatabase
        volumes:
            - ~/dbs/pollsDatabase:/data/db
        ports:
            - 27017:3007
        networks: 
            - pollsdb
    users-service:
        build: ./usersService
        ports:
            - 3004:3004
        networks: 
            - users
            - usersdb
        depends_on:
            - users-database
    poll-service:
        build: ./pollService
        ports:
            - 3003:3003
        depends_on: 
            - polls-database
        networks: 
            - pollsdb
            - api
    main-service:
        build: ./mainService
        ports:
            - 3002:3002
        networks: 
            - pollsdb
            - users
            - api
        depends_on:
            - users-database
            - users-service
            - polls-database

networks:
    users:
        driver: overlay
        internal: true
    usersdb:
        driver: overlay
        internal: true
    pollsdb:
        driver: overlay
        internal: true
    api:
```

And here is my ecosystem.config.js

```
module.exports = {
  apps : [{
    name: 'API',
    script: 'app.ts',

    // Options reference: https://pm2.io/doc/en/runtime/reference/ecosystem-file/
    instances: 1,
    autorestart: true,
    env: {
      NODE_ENV: 'development'
    },
    env_production: {
      NODE_ENV: 'production'
    }
  }]
};

```

```
pm2:paths pm2 home resolved to /root/.pm2 /root +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +0ms
  pm2:client Using RPC file /root/.pm2/rpc.sock +0ms
  pm2:client Using PUB file /root/.pm2/pub.sock +0ms
  interactor:client [PING INTERACTOR] Trying to connect to Interactor daemon +0ms
  axon:sock connect attempt null:/root/.pm2/interactor.sock +0ms
  pm2:client [PING PM2] Trying to connect to server +4ms
  axon:sock connect attempt null:/root/.pm2/rpc.sock +2ms
  axon:sock error ENOENT +2ms
  axon:sock ignored ENOENT +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +1ms
  axon:queue flush 0 messages +0ms
  axon:sock closing +1ms
  axon:sock closing 1 connections +0ms
  pm2:client Daemon alive +5ms
  axon:sock remove socket 0 +1ms
  pm2:client Launching RPC client on socket file /root/.pm2/rpc.sock +1ms
  axon:sock connect attempt null:/root/.pm2/rpc.sock +0ms
  axon:sock connect +1ms
  axon:sock add socket 0 +0ms
  axon:queue flush 0 messages +2ms
  pm2:client RPC Connected to Daemon +1ms
  pm2:cli Now connected to daemon +0ms
  pm2:client Calling daemon method pm2:getVersion on rpc socket:/root/.pm2/rpc.sock +5ms
  pm2:client Calling daemon method pm2:getVersion on rpc socket:/root/.pm2/rpc.sock +2ms
  pm2:client Calling daemon method pm2:getReport on rpc socket:/root/.pm2/rpc.sock +2ms
===============================================================================
--- PM2 REPORT (Sat Dec 08 2018 05:34:40 GMT+0000 (Coordinated Universal Time)) 
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 3.2.2
node version         : 11.2.0
node path            : not found
argv                 : /usr/local/bin/node,/usr/local/bin/pm2-runtime,start,ecosystem.config.js
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 3.2.2
node version         : 11.2.0
node path            : /usr/local/bin/pm2
argv                 : /usr/local/bin/node,/usr/local/bin/pm2,report
argv0                : node
user                 : undefined
uid                  : 0
gid                  : 0
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : linux
type                 : Linux
cpus                 : Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
cpus nb              : 8
freemem              : 9924804608
totalmem             : 16734646272
home                 : /root
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/root/.pm2/rpc.sock +23ms
===============================================================================
--- PM2 list -----------------------------------------------
  pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/root/.pm2/rpc.sock +2ms
┌──────┬────┬──────┬────────┬────────┬─────┬────────┬───────────┐
│ Name │ id │ mode │ status │ ↺      │ cpu │ memory │
├──────┼────┼──────┼────────┼────────┼─────┼────────┼───────────┤
│ API  │ 0  │ N/A  │ fork   │ online │ 0   │ 99.4%  │ 79.9 MB   │
└──────┴────┴──────┴────────┴────────┴─────┴────────┴───────────┘
===============================================================================
--- Daemon logs --------------------------------------------
┌──────┬────┬──────┬────────┬────────┬─────┬────────┬───────────┐
│ Name │ id │ mode │ status │ ↺      │ cpu │ memory │
├──────┼────┼──────┼────────┼────────┼─────┼────────┼───────────┤
│ API  │ 0  │ N/A  │ fork   │ online │ 0   │ 0%     │ 79.9 MB   │
└──────┴────┴──────┴────────┴────────┴─────┴────────┴───────────┘
 Use `pm2 show <id|name>` to get more details about an app
  interactor:client Disconnect RPC +50ms
  interactor:client RPC not launched +1ms
  axon:sock closing +41ms
  axon:sock closing 1 connections +0ms
  axon:sock remove socket 0 +1ms
  pm2:client PM2 RPC cleanly closed +8ms
  pm2:cli This command took 0.049s to execute +0ms

```
