### ISSUE TITLE
Feature: Support ENV replacement in ecosystem files

### ISSUE THREAD

**Issue by pke** [Unitech/pm2#4531]
Similar to https://github.com/Unitech/pm2/issues/4514 but I think easier to implement and more flexible

```yaml
deploy:
  production:
    user: $SSH_USER,
    host: $SSH_HOST
...
```
