### ISSUE TITLE
Feature Request: Alias name for UAT

### ISSUE THREAD

**Issue by boxsnake** [Unitech/pm2#4653]
## What's going wrong?
I am running both uat and online instances in the same machine, so I have to use `xxx-uat` and `xxx` to distinguish them. Is it possible to use an alias for the same tasks?

I do not want to use both `--env` and `--only`, I just want to use only one task with different `env_*`s, something like this:
```yaml
apps:
  - script: ./app.js
    name: app
    env_development:
      ENV: development
    env_uat:
      ENV: uat
```

I want to call with `pm2 start app.yml --env development` for application named "app", and `pm2 start app.yml --env uat` for application named "app-uat".

I'll approciate it if you can response to the request. Thank you.
