### ISSUE TITLE
Changing the default value for kill_retry_time is never applied

### ISSUE THREAD

**Issue by danielmoonactive** [Unitech/pm2#4714]
## What's going wrong?

I set the `kill_retry_time` parameter at pm2 startup to the value 2000. However, when stopping a process via `pm2 stop all` - pm2 does not honor the parameter value passed in the configuration, and still uses the default one, which is 100 (ms). This is evident by seeing the following every 100ms in the pm2 log while stopping the process, instead of seeing this every 2 seconds:

`pid=1111 msg=failed to kill - retrying in 100ms`

I have some script that's running during shutdown, so it's fine that pm2 is trying once in a while to check if the process finished its shutdown stuff. However, I want it to be more than 100 ms, but it seems the configurations does not take affect.

## How could we reproduce this issue?
Start PM2 with the API:

```
  pm2.start(pm2StartupConfigFile, function(err, apps) {
     ...
  });
```

where the `pm2StartupConfigFile` is the following:

```
apps:
  - script: /home/myName/app.js
    name: myName
    instances: 0
    exec_mode: cluster
    autorestart: true
    watch: false
    time: false
    wait_ready: true
    listen_timeout: 150000
    out_file: /tmp/logs/out.log
    error_file: /tmp/logs/error.log
    merge_logs: true
    node_args: --max_old_space_size=4000
    disable_source_map: true
    kill_timeout : 20000
    kill_retry_time: 2000
    env:
      NODE_ENV: production
```
Now restart all the processes, and notice you get the following log every 100ms instead of every 2 seconds:

`pid=1111 msg=failed to kill - retrying in 100ms`
