### ISSUE TITLE
Can I use $VAR inside process.config.yaml?

### ISSUE THREAD

**Issue by fenixsolorzano** [Unitech/pm2#4720]
I'd like to know if the following is possible:

```yaml
apps:
  - script: ./index.js
    name: '${APP_NAME}'
    node_args:
      - '-r source-map-support/register'
```
