### ISSUE TITLE
pm2 laravel queue worker not running jobs but directly running command in console works

### ISSUE THREAD

**Issue by andrew-za** [Unitech/pm2#4756]
When running the `php artisan queue:work` directly in console jobs are processed.

Using pm2 to start the script successfully shows running with no messages in log but jobs are not processed.

Log file:
```
apps:
  - name: laravel-worker
    script: artisan
    exec_mode: fork
    watch: false
    interpreter: php
    instances: 1
    args: "queue:work database --daemon --tries=3 --sleep=2"
```
