### ISSUE TITLE
When pm2 is in cluster mode, does it use 1 core (cpu) per process?

### ISSUE THREAD

**Issue by seungdols** [Unitech/pm2#4905]
## What's going wrong?

I am using pm2 really well for our project service. By the way, I have a question.

I am running a node api on k8s, but I want to use pm2, so I have a question while configuring k8s + pm2 + node api.

```yaml
     resources:
       requests:
         memory: 256Mi
         cpu: 0.1
         ephemeral-storage: 1Gi
       limits:
         memory: 1Gi
         cpu: 2
         ephemeral-storage: 6Gi
```

```js
module.exports = {
   apps: [
     {
       name:'api',
       script:'dist/bundle.js',
       instances: 6,
       autorestart: true,
       watch: false,
       exec_mode:'cluster',
     },
   ],
}
```

I did it as above, but looking at the log of the k8s pod, 6 pm2 processes were constantly restarting.

If you guess, starting with pm2 will allocate 1 cpu core per process? I wonder.

## Supporting information

PM2 log: PM2 version          : 4.5.0
PM2 log: Node.js version      : 12.14.1

```
$ pm2 report
```
