### ISSUE TITLE
Github workflow action timeout error, continues log streamed to console

### ISSUE THREAD

**Issue by vkiranmaniya** [Unitech/pm2#5172]
## What's going wrong?
Executing `pm2 restart --no-daemon` using ssh from github action caused continues log stream and github action exits with `Run Command Timeout!` error.

## How could we reproduce this issue?
I have simple GitHub action that connects to the server using ssh. I'm running the `pm2 restart --no-daemon` from github action and it ends up with continuous pm2 logs stream causing timeout from github action itself.

## Supporting information
Here is the workflow action for deployment
```yml
name: Continuous Integration Custimonial Production

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USER }}

          script: |
            cd ~/demo/demo
            git pull
            npm install --production
            pm2 kill demo
            NODE_ENV=production && pm2 start ecosystem.config.json --no-daemon
            echo 'Deployment successful to digital ocean'
```

Here is the ecosystem config file
```json
{
  "apps": [
    {
      "name": "demo",
      "script": "src/index.js",
      "instances": 1,
      "autorestart": true,
      "watch": false,
      "time": true,
      "env": {
        "NODE_ENV": "production"
      }
    }
  ]
}

```

This is the error log at the end of github action log
```
err: Run Command Timeout!
2021/09/09 08:51:03 Error: command timeout
```
