### ISSUE TITLE
support YAML for app declaration

### ISSUE THREAD

**Issue by rlidwka** [Unitech/pm2#578]
I'm looking at [this](https://github.com/meteor/meteor/issues/1116#issuecomment-48982351), and just realizing that is not a meteor issue. It's pm2 issue. JSON just doesn't work quite right when used for config files.

If we add yaml support, @dandv 's example could be rewritten like this:

```yaml
name: frontend
script: main.js

env:
  NODE_ENV: production
  METEOR_SETTINGS: |
    {
      "Kadira": {
         "appId": "...",
         "appSecret": "..."
      },
      "public": {
        "analytics_api_key": "xxx",
        ...
      }
    }
```

... solving all issues with escaping quotes.

I don't even mention that in production environments those files need to be commented out (which json doesn't support), or a handy feature of yaml that allows to define constants and reuse it anywhere in the same file (say, define "max_restarts" once and use that value for every app).

This would also remove the need for single quotes in "args" (and therefore eval(), see #568, which one could see as a possible security issue), replacing that with double quotes and a regular JSON.parse().
