### ISSUE TITLE
pm2 fails to return correctly in ansible

### ISSUE THREAD

**Issue by jpmerritt** [Unitech/pm2#88]
When pm2 commands are run through ansible they operate correctly but fail to return in a way that ansible recognises causing ansible to be stuck at that location waiting for a correct exit. 

For example a command like 
$ pm2 start pm2-start.json
will run the script but hang afterwards.  If you kill that script in a different terminal session the still running script in the other session will finally continue.  You can also work around the problem by attaching >& /dev/null to the end of the script so the ansible command might end up looking like this.  

shell: pm2 start pm2-start.json >& /dev/null chdir=~/ executable=/bin/bash

**Comment by sjwoodr** [comment]
I have the same problem with running any "pm2" command via SaltStack.  After struggling with it for some time, I finally found a workaround:

```
init-pm2:
    cmd.run:
      - name: env PATH=$PATH:/opt/node/node-v0.12.4-linux-x64/bin pm2 startup linux -u someuser
      - require:
        - cmd: install-npm-pm2
      - user: root
```

Even though the salt-minion process runs as root, without that explicit "- user: root" in there, the command will hang.  This can be a highstate or even a cmd.run for the specific state that executes pm2 commands.  Any pm2 command would hang: ping, startup, show, etc...    I theorize that having the -user option in the state causes salt to spawn a new shell and that shell is sufficiently different than the one running the command by default.  (shrug)
